### ISSUE TITLE
Brace style

### ISSUE THREAD

**Issue by stief510** [prettier/tslint-config-prettier#280]
Hi,

I am trying to use brace style’s stroustrup rule within my tslint.json’s rules object. The error shows in the linter but then Prettier overrides it and defaults back to 1tbs style

**Comment by ikatyang** [comment]
Hi, this package is used for disabling rules that may conflict with Prettier via `extends` field, so we are not able to override rules in `rules` field since it takes precedence over `extends`.

Since Prettier always formats them with 1tbs style, I'd suggest you to remove this rule in `rules` field.

**Comment by stief510** [comment]
My understanding is that this package allows you to turn off some of prettier's rules that conflict with tslint's rules. brace-style is one of the rules listed in tslint-eslint-rules that I am trying to extend

**Comment by ikatyang** [comment]
This package is actually turning off some TSLint rules that may conflict with Prettier.

> Do you want to use [TSLint](https://palantir.github.io/tslint/) and [Prettier](https://github.com/prettier/prettier) without conflicts? `tslint-config-prettier` disables all [conflicting rules](https://unpkg.com/tslint-config-prettier) that may cause such problems. Prettier takes care of the formatting whereas tslint takes care of all the other things.

**Comment by stief510** [comment]
Ok but then tslint-config-prettier is not turning off the brace-style rule because when I make it different, tslint gives me an error but Prettier keeps the formatting that way

For example, if I have the following:
```
if () {
...
} else {
...
}
```
tslint complains. If I move `else` to the next line, Prettier will then move it back

**Comment by ikatyang** [comment]
Since this package is desinged to be used in the `extends` field, there are only two possible way to solve your issue:

- remove `brace-style` from your `rules` field (in `tslint.json`). We are not able to override rules in `rules` field since it takes precedence over `extends` field.

  ```diff
   // tslint.json
   {
     "rules": {
  -    "brace-style": [true, "stroustrup"]
     }
   }
  ```
- create a new `tslint.json` that extends the original `tslint.json` and `tslint-config-prettier`:
  ```jsonc
  // tslint.json
  {
    "extends": ["./path/to/original/tslint.json", "tslint-config-prettier"]
  }
  ```
